### ISSUE TITLE
网页批注规则支持通配符及带端口

### ISSUE THREAD

**Issue by seanwwh** [it5200/flomoPlus#100]
网页批注规则白名单希望增强一下功能：
1、支持通配符，比如http://*.abc.com
2、支持带端口，比如http://abc.def.com:8080

**Comment by it5200** [comment]
新版本2.0 beta 支持拖拽，不再出现在iframe 里，所以这个白名单暂时下线了

2.0 beta  体验提示 https://github.com/it5200/flomoPlus/discussions/90
