### ISSUE TITLE
设置API时希望能够不加默认标签

### ISSUE THREAD

**Issue by JayYa** [it5200/flomoPlus#101]
希望不加tag也能使用

_Originally posted by @ttttmr in https://github.com/it5200/flomoPlus/issues/48#issuecomment-878260770_

**Comment by it5200** [comment]
why?

**Comment by JayYa** [comment]
因为记笔记就是在不同网页上记的，为什么必须要有一个统一的默认标签？
如果我在设置里加了一个 #网页 的标签，每次发送前还要把这个标签删了，然后再输入自己想要的标签

**Comment by it5200** [comment]
标签是为了给鼠标右键用的，如果是markweb或者其他的可以手动删除哈，具体查看下图


![image](https://user-images.githubusercontent.com/19451694/146626373-fa2327f0-1bf3-44c6-8ff6-a3dcb0faca1e.png)

**Comment by JayYa** [comment]
我就是单纯的不希望每次都要手动删除...
