### ISSUE TITLE
Edge 浏览器，白名单设置失败

### ISSUE THREAD

**Issue by DuanYihui** [it5200/flomoPlus#105]
白名单设置提交后，刷新对应页面不会生效
再次点开设置时，发现白名单已经被清空

**Comment by it5200** [comment]
好的，新版本增加了判断iframe的机制，可以去下载新版本体验下啊

麻烦先用这个过渡下哈（2.0 beta）
https://github.com/it5200/flomoPlus/discussions/90   现在还是beta阶段哈，想用的可以去体验下，建议换个浏览器安装哈

**Comment by extrastu** [comment]
现在2.0已经上架了，可以去chrome商店搜索安装，edge的还在审核中
