### ISSUE TITLE
能否将网页笔记中用的*、#等符号转换成相应的项目符号

### ISSUE THREAD

**Issue by HuaQing947** [it5200/flomoPlus#107]
你好，想问一下flomo的Chrome插件中，是否支持将网页笔记中用的*、#等符号转换成（在flomoapp.com查看时)<img width="427" alt="WechatIMG1600" src="https://user-images.githubusercontent.com/96765820/148745906-46be362f-2869-4470-b0b0-1c0fee6dbbcf.png">？

**Comment by it5200** [comment]
抱歉暂时不支持
