### ISSUE TITLE
我想在本仓库的基础上做开发，但是我并没有找到可以使用的代码

### ISSUE THREAD

**Issue by Mran** [it5200/flomoPlus#108]
有一个猜测，不一定对，是不是忘记上传代码了，只上传了release

**Comment by it5200** [comment]
抱歉目前只开源了初始版本，初始版本在之前从版本里删掉，想看的话可以看commit记录

**Comment by Mran** [comment]
好的,我只有从头造轮子了.

**Comment by it5200** [comment]
主要是版本一直没有稳定下来所以新版本暂时没有开源
