### ISSUE TITLE
导航栏 返回缺失

### ISSUE THREAD

**Issue by yangyiarise** [it5200/flomoPlus#117]
导入第三方数据-微信读书-<进入特定书目后 > 无法返回前一页
![image](https://user-images.githubusercontent.com/98093788/150331487-1dc523bf-a3fc-431b-8d36-318660a25ac9.png)

**Comment by extrastu** [comment]
好的，是darkmode适配的问题，下个版本修复

**Comment by extrastu** [comment]
chrome商店已经上架
