### ISSUE TITLE
网站 URL 会被覆写，自动添加 hash #

### ISSUE THREAD

**Issue by superman66** [it5200/flomoPlus#118]
## 版本
2.0.41

## 描述
该插件会覆写网站的 url，自动带上 #。影响到了其他网站的正常功能。如下：
`https://xxxx.com/path#/`

同时控制台有报错，报错内容如下：
![image](https://user-images.githubusercontent.com/12592949/150507937-5df190dc-f00c-4e95-8972-4e16cb23a12e.png)

**Comment by extrastu** [comment]
好的

**Comment by extrastu** [comment]
正在解决

**Comment by extrastu** [comment]
已经修复等待更新 ，git https://github.com/it5200/flomoPlus/releases/tag/v2.0.5

**Comment by extrastu** [comment]
目前chrome 商店已经上架

**Comment by superman66** [comment]
谢谢~
