### ISSUE TITLE
访问一些站点的时候，会自动在域名后面加#，导致无法正常使用

### ISSUE THREAD

**Issue by maxminly** [it5200/flomoPlus#119]
![image](https://user-images.githubusercontent.com/14090175/151287893-15908b50-c472-4a42-8962-2621fbdf184f.png)
![image](https://user-images.githubusercontent.com/14090175/151287994-36901b13-a659-45c6-8539-48d1ab37fe57.png)

在部分使用“#”做路由的网站内，可能出现各种异常，希望能够fix
环境
Microsoft Edge
版本 97.0.1072.69 (官方内部版本) (x86_64)

**Comment by extrastu** [comment]
麻烦去chrome商店升级为最新的版本，最新版本已经修复这个问题，edge的还在审核
