### ISSUE TITLE
微信读书无法读取批注

### ISSUE THREAD

**Issue by eblessme** [it5200/flomoPlus#123]
之前可以读取批注和笔记两个部分的，现在为何只能用“笔记”而不能用批注了，重新安装了也没用。批注对于我来说真的很重要5555555，希望我能在此询问到解决的方法

**Comment by extrastu** [comment]
你好，你使用的是哪个版本的

**Comment by extrastu** [comment]
我知道了，是我的问题，下个版本解决下

**Comment by eblessme** [comment]
谢谢大大🥰🥰🥰🥰



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月28日(周一) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [extrastu/flomoPlus] 微信读书无法读取批注 (Issue #123)




 
我知道了，是我的问题，下个版本解决下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by extrastu** [comment]
非常不好意思

**Comment by eblessme** [comment]
怎会不好意思！！应该是我们非常感谢你的付出🥺🥺



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月28日(周一) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [extrastu/flomoPlus] 微信读书无法读取批注 (Issue #123)




 
非常不好意思
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by extrastu** [comment]
![image](https://user-images.githubusercontent.com/19451694/155911636-4a8122fa-bcc2-4b1f-b806-6cca5dfcce4d.png)
已经修复，下个版本就可以正常使用了

**Comment by extrastu** [comment]
新版本已经上线了，https://chrome.google.com/webstore/detail/flomoplus/kcijjmomofpdcpeiagibojhjifhegepj 点击下载体验

**Comment by eblessme** [comment]
谢谢大大🥰🥰我这就火速去更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月2日(周三) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [extrastu/flomoPlus] 微信读书无法读取批注 (Issue #123)




 
新版本已经上线了，https://chrome.google.com/webstore/detail/flomoplus/kcijjmomofpdcpeiagibojhjifhegepj 点击下载体验
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
