### ISSUE TITLE
flomoPlus插件导致notion网页版无法打开

### ISSUE THREAD

**Issue by liangxiaorui** [it5200/flomoPlus#126]
输入地址：https://www.notion.so/desktop
直接提示：
Application error: a client-side exception has occurred (see the browser console for more information).
截图如下：
<img width="814" alt="image" src="https://user-images.githubusercontent.com/8081152/159606358-85e4e89a-29ae-4876-9554-9c250279da35.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/8081152/159606396-bdd2cfc9-d54b-4c32-bb92-c2c1313f9f33.png">

若在chrome中禁用flomoPlus，则可正常访问notion

**Comment by extrastu** [comment]
麻烦把你现在使用的flomoplus版本发下，我试了下是没问题的

**Comment by liangxiaorui** [comment]
> 

我调查发现确实不是flomoplus的问题，是和简悦插件冲突，把notion.so加入简悦的黑名单就解决了。

**Comment by extrastu** [comment]
> > 
> 
> 我调查发现确实不是flomoplus的问题，是和简悦插件冲突，把notion.so加入简悦的黑名单就解决了。

好的
