### ISSUE TITLE
需求：可否增加强化版的回顾功能？

### ISSUE THREAD

**Issue by KeXue-NJU** [it5200/flomoPlus#136]
flomo自带的每日回顾和随机漫步无法满足我当前回顾一些tag的需求。

希望flomoPlus有这样的功能：

- 输入：某个标签，想回顾的memo数n
- 输出：该标签下的随机n条memo

进一步的，该功能可以与“筛选”结合，允许对输出的标签做时间之类的限制

**Comment by extrastu** [comment]
呃，不好意思，这个不会做，可以等后续官方可能会加强
