### ISSUE TITLE
[FEATURE REQUEST] 直接对高亮内容进行批注和添加标签

### ISSUE THREAD

**Issue by qiuxiaomu** [it5200/flomoPlus#139]
我不知道是不是我的用法有问题, 我一般用flomo来针对我读过的内容进行注释, 写下自己的想法, 变成自己的知识. 但是这个插件, 只能针对整个网页进行记录, 然后对整个网页进行批注, 大部分时候我只关注的是一个段落而已, 更多的是希望可以对高亮段落进行注释, 然后可以包含URL方便复读.

**Comment by qiuxiaomu** [comment]
桥豆麻袋, 我刚翻看了下flomo官网, 

```
记录卡片的原则
不复制：用自己的话写，不去复制粘贴，避免收藏全文；
**抓重点：不需要摘抄全文，记录有启发的部分；**
为自己：不过度考虑修辞排版，只为自己记录；
别贪心：避免记录太多，关键在于持续不断；
```

难道flomo的意思是要我用自己的话, 总结全文列出要点?? 这个完全是提升我阅读理解能力.. 

但是可不可以针对片段进行这个自我总结呢? 嗯, 就是我记录的话, 我还是记录我对某个片段的想法, 但是有没有办法可以方便我定位这个片段在网页的位置? 目前只有URL可以被保存下来, 下一次我读自己的想法, 想要复读一下原文片段的时候, 我就需要去通读全文找片段, 有没有办法可以在添加memo的时候, 把段落的信息也添加到memo里面, 这个我下次就可以知道我的memo是针对哪个片段了.

**Comment by qiuxiaomu** [comment]
今天细读了一下创始人少楠关于flomo的分享, 我发现其实手机场景, 讨论场景和网页场景都会有用到摘抄的时候, 并且现在的IOS的快捷指令就可以高亮摘抄并批注. 真的希望可以加入这个功能到网页版, 辛苦大佬了.

**Comment by extrastu** [comment]
![image](https://github.com/extrastu/flomoPlus/assets/19451694/250d0f42-c435-4aea-8632-773083187956)
 你好，可以先选择内容然后使用鼠标右键发送到 flomo ，可以在flomo 里进行批注啦
