### ISSUE TITLE
web SQL 已废弃

### ISSUE THREAD

**Issue by Elliott-Hu** [it5200/flomoPlus#140]
开发者你好，新版chrome浏览器即将废弃 WebSQL ，我看插件中依赖到相关的功能可能用不了了，需要想一下替代方案了。

https://developer.chrome.com/blog/deprecating-web-sql/

**Comment by Elliott-Hu** [comment]
<img width="1058" alt="image" src="https://github.com/extrastu/flomoPlus/assets/16644716/3bc07189-5f97-439c-915a-d998c1fcec1c">

**Comment by extrastu** [comment]
好的，我这边也发现了，下版本修复下

**Comment by extrastu** [comment]
已经修复
