### ISSUE TITLE
Chrome 浏览器侧边栏支持

### ISSUE THREAD

**Issue by rainyear** [it5200/flomoPlus#141]
希望可以增加 chrome 浏览器插件侧边栏兼容，边浏览网页边记笔记很好用！

<img width="536" alt="image" src="https://github.com/extrastu/flomoPlus/assets/3953966/988696f7-1287-4572-8f2e-e3ca04428647">

**Comment by extrastu** [comment]
> 希望可以增加 chrome 浏览器插件侧边栏兼容，边浏览网页边记笔记很好用！
> 
> <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/3953966/292668100-988696f7-1287-4572-8f2e-e3ca04428647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTU2NjEsIm5iZiI6MTcwMzU1NTM2MSwicGF0aCI6Ii8zOTUzOTY2LzI5MjY2ODEwMC05ODg2OTZmNy0xMjg3LTQ1NzItOGYyZS1lM2NhMDQ0Mjg2NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDE0OTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI4MDk2MTY1N2YyODZkOWQ5YThhNmZmNmUzMzRlZGIyOGVkNTQzYWNmZGU4Nzk5YTczODcxYWFjMjQyNmY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t6DyoGGckvfkzaC3wFf_fZGjTXi4OB1WWXxeY0yHs9w">

我来研究下

**Comment by extrastu** [comment]
看了下，支持侧边栏需要把 插件版本升级为 v3，考虑了下，暂时不做支持

**Comment by extrastu** [comment]
![image](https://github.com/extrastu/flomoPlus/assets/19451694/7e225481-ea53-45df-8eb1-ce6d5cda4599)
可以试试我的新作品，sidebrowser，可以把flomo放在侧边栏， https://chromewebstore.google.com/detail/side-browser/pcamlcdojeblfddaeoajojpjnenniedk
