### ISSUE TITLE
flomoplus菜单页显示不全

### ISSUE THREAD

**Issue by Whatswrong404** [it5200/flomoPlus#142]
![临时0107](https://github.com/extrastu/flomoPlus/assets/70121735/0559d90a-c544-48bf-8532-70d1675af301)
这个菜单只有一个“分享”没有什么统计字数和批量删除了，试过重装也不好用，edge和chrome都有这个问题。

**Comment by extrastu** [comment]
> ![临时0107](https://github.com/extrastu/flomoPlus/assets/70121735/0559d90a-c544-48bf-8532-70d1675af301)
> 
> 这个菜单只有一个“分享”没有什么统计字数和批量删除了，试过重装也不好用，edge和chrome都有这个问题。
> 
> 

因为统计字数和批量删除，flomo 已经支持，所以 flomoplus 的下架了（算转正吧）

**Comment by Whatswrong404** [comment]
请问怎么在flomo网页端找到批量删除呢？我没能在flomo的网页、电脑、手机端找到那种可以选中好多条，然后一口气批量删除的图标

**Comment by extrastu** [comment]
> 请问怎么在flomo网页端找到批量删除呢？我没能在flomo的网页、电脑、手机端找到那种可以选中好多条，然后一口气批量删除的图标

因为统计字数和批量删除，flomo 已经支持，所以 flomoplus 的下架了（算转正吧）
