### ISSUE TITLE
谷歌浏览器的flomo小程序拓展出现bug

### ISSUE THREAD

**Issue by weisheng940717** [it5200/flomoPlus#49]
谷歌浏览器的小程序 无法发送到flomo，同时输入标签后无法回车，以及无法进行删除文字

**Comment by it5200** [comment]
谷歌浏览器的小程序 ? 没明白

**Comment by weisheng940717** [comment]
sorry  我说错了，是 flomo Plus（Chrome 扩展），在其他网页都没问题，但是在notion 就有这个问题，
https://www.notion.so/4d92410d370849c1be0bde496b6d60bb

**Comment by weisheng940717** [comment]
https://www.notion.so/4d92410d370849c1be0bde496b6d60bb

**Comment by it5200** [comment]
麻烦截个图我看下，现在还是不大明白

**Comment by weisheng940717** [comment]
[image: image.png]就是产品沉思录的这个页面里，然后这个flomo拓展程序不能按回车键，打错字了也不能产出这样~

extrastu ***@***.***> 于2021年7月16日周五 上午11:13写道：

**Comment by weisheng940717** [comment]
打错字了也不能删除

陈志生 ***@***.***> 于2021年7月16日周五 下午9:35写道：

**Comment by it5200** [comment]
。。。抱歉没看到你发的图片
