### ISSUE TITLE
网页批注规则保存失败

### ISSUE THREAD

**Issue by Y545329005** [it5200/flomoPlus#51]
在网页批注--设置规则里，添加了白名单网址，当时操作的是https://www.tapd.cn/
提交以后，页面有显示已添加成功。
但是刷新https://www.tapd.cn/之后还是会出现批注logo，再进入白名单配置页，之前保存的就消失了_(:з」∠)_

**Comment by extrastu** [comment]
现在2.0已经上架了，可以去chrome商店搜索安装，edge的还在审核中，在2.0中移除了这个设置，已经修复iframe问题
