### ISSUE TITLE
同一个插件，两个不同入口，中英文和格式不一样

### ISSUE THREAD

**Issue by orzcc** [it5200/flomoPlus#52]
工具栏的入口
![image](https://user-images.githubusercontent.com/402270/127083649-d33f2a8d-76ba-45ce-9836-0d01443dc410.png)

网页内右下角的入口
![image](https://user-images.githubusercontent.com/402270/127083569-001b01fc-e282-4436-8c42-abedb7373ef5.png)
![image](https://user-images.githubusercontent.com/402270/127083529-a5203453-3550-47c2-b98a-b04a0924b3f8.png)

**Comment by it5200** [comment]
是的，设计之初是不一样的
