### ISSUE TITLE
需求反馈：希望增加批量删除功能

### ISSUE THREAD

**Issue by Juneflyfire** [it5200/flomoPlus#73]
在导入微信读书笔记时，可以整本导入，但是多次在flomo上阅读后，可能觉得有些不是很有价值，单条删除较为繁琐。

**Comment by it5200** [comment]
好的，我看看

**Comment by Juneflyfire** [comment]
> 好的，我看看
回复速度点赞，感谢回复~也感谢这个好产品的诞生~

**Comment by lylunula** [comment]
+1~

**Comment by extrastu** [comment]
现在2.0已经上架了，可以去chrome商店搜索安装，edge的还在审核中
