### ISSUE TITLE
绑定导入的微信读书、得到账号无法在网页上退出或更换

### ISSUE THREAD

**Issue by caitian94** [it5200/flomoPlus#74]
因为我第一次导入得到笔记的时候，错误地授权了一个得到小号，结果没有找到哪里可以把这个得到小号退出来。目前也没有办法绑定大号，用不起来了。

**Comment by it5200** [comment]
> 因为我第一次导入得到笔记的时候，错误地授权了一个得到小号，结果没有找到哪里可以把这个得到小号退出来。目前也没有办法绑定大号，用不起来了。

在得到web页面退出重新登录就行了
