### ISSUE TITLE
网页批注位置有时候被遮挡

### ISSUE THREAD

**Issue by tianlelyd** [it5200/flomoPlus#80]
因为有些网页会有右侧工具栏「比如说得到dedao.cn」，有时候就刚好跟flomoPlus的位置重叠，这个时候就不太方便去点了！咱们工具是不是可以提供一个自定义位置的功能呢？以避免这种现象？

**Comment by it5200** [comment]
最新版本可以暂时性的删除网页标注的icon，刷新就会再看到

**Comment by extrastu** [comment]
现在2.0已经上架了，可以去chrome商店搜索安装，edge的还在审核中，支持了拖拽
