### ISSUE TITLE
多看阅读无法使用

### ISSUE THREAD

**Issue by nanvon** [it5200/flomoPlus#87]
使用微信扫码登录多看，但是依旧提示没有登录，刷新、重新登录、清除浏览器数据后还是这样

**Comment by it5200** [comment]
收到，我来check下

**Comment by extrastu** [comment]
现在2.0已经上架了，可以去chrome商店搜索安装，edge的还在审核中

**Comment by nanvon** [comment]
问题已解决，辛苦！
