### ISSUE TITLE
扩展选项点进来-弹窗太小

### ISSUE THREAD

**Issue by sunjiefeng** [it5200/flomoPlus#93]
![image](https://user-images.githubusercontent.com/46740955/144417682-d513f818-d3c5-4f67-89ae-c99126b1128d.png)

**Comment by it5200** [comment]
设置页面不要在这里打开，麻烦从点击flomoplus icon 里的设置进入

**Comment by extrastu** [comment]
2.0版本已经移除，不需要进入这个页面设置
